workflows:
  build-unsigned-apk:
    name: Build Unsigned APK
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 17
        NODE_VERSION: 18
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/app-release-unsigned.apk